ci(pull-request.yml): adding Branch Name Convention validation

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -2,11 +2,26 @@ name: Test & Lint Feature Branch
 
 on:
   pull_request:
+    types:
+      - opened
 
 jobs:
-  test-coverage:
+  enforce-branch-naming:
     runs-on: ubuntu-latest
 
+    steps:
+      - name: Check Branch Name Convention
+        run: |
+          branch_name=$(echo $GITHUB_REF | sed -e 's,.*/\(.*\),\1,')
+          if [[ ! "$branch_name" =~ ^(feat|fix|docs|style|refactor|perf|test|ci|chore)/.*$ ]]; then
+            echo "Invalid branch name. Branch names must follow the convention."
+            exit 1
+          fi
+
+  test-coverage:
+    runs-on: ubuntu-latest
+    needs: enforce-branch-naming
+    if: needs.enforce-branch-naming.result == 'success'
     steps:
       - uses: actions/checkout@v2
 
